import { Icons } from "@/components/ui/icons";

export const DATA = {
  name: "Suman Khadka",
  initials: "SK",
  url: "",
  description:
    "A passionate software developer studying currently at University of Akron",
  summary:
    "Currently a senior at [UAkron](https://uakron.edu). Majoring in Computer Science and minoring in Statistics.\n\n" +
    "- Cooped at [Pile Dynamics](#work)\n\n" +
    "- Active member of [ACM Chapter](https://www.acm.org/chapters/students)\n" +
    "- Student Ambasador for [Everest Nepalese Student Organization](https://www.instagram.com/uakronenso/)\n" +
    "- Likes to swim and play soccer\n\n",

  avatarUrl: "/me.png",
  skills: [
    {
      category: "Languages",
      items: ["Javascript", "TypeScript", "C#", "C++", "Python"],
    },
    {
      category: "Frameworks and Database",
      items: [
        "React",
        "React Native",
        "NodeJS",
        "Next.js",
        "ASP.NET",
        "Tailwind css",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Supabase",
        "Prisma",
      ],
    },
    {
      category: "Tools",
      items: ["Azure DevOps", "Swagger", "Git"],
    },
  ],
  navbar: [
    { href: "/", icon: Icons.home, label: "Home" },
    { href: "/blog", icon: Icons.blog, label: "Blog" },
  ],

  social: {
    GitHub: {
      name: "https://github.com/sk394",
      url: "https://github.com/sk394",
      icon: Icons.github,
    },
    LinkedIn: {
      name: "https://www.linkedin.com/in/iamsumankd",
      url: "https://www.linkedin.com/in/iamsumankd",
      icon: Icons.linkedin,
    },
    email: {
      name: "sk394@uakron.edu",
      url: "sk394@uakron.edu",
      icon: Icons.email,
    },
  },

  work: [
    {
      company: "Pile Dynamics",
      href: "https://www.pile.com",
      badges: [],
      location: "Onsite",
      title: "Software Developer Coop",
      logoUrl: "https://www.pile.com/wp-content/themes/pile/img/logo.svg",
      start: "Jan 2023",
      end: "Dec. 2024",
      description:
        "- Developed backend API endpoints in **.NET** for the Atlas project, which serves professionals in the deep foundation industry.\n" +
        "- Used **Next.Js** to create UI components for data visualization generated by PDI products.\n" +
        "- Utilized DBeaver to write and execute **PostgreSQL** queries for testing, inserting data, and debugging databases.\n" +
        "- Utilized **Cypress** and **Vitest** for frontend testing, ensuring code quality and reducing bugs in production.\n" +
        "- Worked on an Agile team with daily scrum meetings utilizing development pipeline software i.e. **Azure DevOps**.\n" +
        "- Conducted unit and integration testing of API endpoints, addressed bugs in production, and improved the frontend code.\n\n",
    },
    {
      company: "The EX[L] Center at UA",
      href: "https://www.uakron.edu/exl/",
      badges: [],
      location: "Onsite",
      title: "Data Collection Student Assistant",
      logoUrl:
        "https://www.uakron.edu/application/themes/uakron-2/images/stacked-ua.svg",
      start: "Aug 2022",
      end: "Present",
      description:
        "- Helped the University students to connect with the EX[L] initiated programs like [Un]Classes, community-engaged learning.\n" +
        "- Provided technical assistance to the team and worked on spreadsheets, EXL file management, and handling.\n" +
        "- Worked on collecting data and resources from different organizations and research institutes for the Collaboratory project of the University of Akron.\n\n",
    },
    {
      company: "Bierce Library at UA",
      href: "https://www.uakron.edu/libraries/",
      badges: [],
      location: "Onsite",
      title: "Student Supervisor",
      logoUrl: "https://live.staticflickr.com/2104/2825031511_a170f75ce8_b.jpg",
      start: "Aug 2021",
      end: "Present",
      description:
        "- Performed check out and check in of library materials from a public service desk.\n" +
        "- Provided basic level research assistance, printing assistance, & and processes lending of technology equipment to patrons.\n\n",
    },
  ],
  education: [
    {
      school: "University of Akron",
      href: "https://www.uakron.edu",
      degree: 'Undergraduate "Computer Science"',
      logoUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/University_of_Akron_seal.svg/1200px-University_of_Akron_seal.svg.png",
      start: "2021",
      end: "2025",
    },
    {
      school: "National School of Sciences",
      href: "https://nist.edu.np/",
      degree: "Associate",
      logoUrl:
        "https://nss.edu.np/wp-content/themes/nss_theme/assets/img/logo.png",
      start: "2017",
      end: "2019",
    },
  ],
  projects: [
    {
      title: "Pickle Selling E-commerce Website",
      href: "https://github.com/sk394/Swadista-Achar",
      dates: "",
      active: true,
      description: `Designed a full-stack pickle-selling e-commerce website with features like inventory management, admin dashboard, delivery mode change, etc.
        Developed a user-friendly and responsive front end with React.
        Built a secure back-end with Node.js, Express framework, and MongoDB.`,

      technologies: ["React", "Mongodb", "Redux"],
      links: [
        {
          type: "Source",
          href: "https://github.com/sk394/Swadista-Achar",
          icon: <Icons.github className="size-3" />,
        },
      ],
      image: "/pickle.gif",
      video: "",
    },
    {
      title: "Summu",
      href: "https://summu.vercel.app/",
      dates: "An AI Tool- ChatGPT alternative",
      active: true,
      description: `·Designed an AI SaaS tool that uses OpenAI and Replicate APIs to provide various services like Chat completion, Video and Audio Generation, and code completion.
Integrated the clerk API for secured sign-ups and logins of the users. Used Next.js library with nested routing for working in the backend and front end.`,
      technologies: [
        "Next.js",
        "Typescript",
        "TailwindCSS",
        "Clerk for authentication",
      ],
      links: [
        {
          type: "Website",
          href: "https://summu.vercel.app/",
          icon: "",
        },
        {
          type: "Source",
          href: "https://github.com/sk394/Summu",
          icon: <Icons.github className="size-3" />,
        },
      ],
      image: "/ai.gif",
      video: "",
    },
    {
      title: "Online BookStore",
      href: "https://nepbooks.azurewebsites.net/",
      dates: "",
      active: true,
      description: `Designed and developed an online bookstore using ASP.NET MVC framework with C#.
Developed a detailed user interface using HTML, CSS, and Bootstrap framework. Integrated secured login system using Microsoft’s ASP.NET identity membership system.`,
      technologies: ["ASP.NET", "C#", "BootStrap"],
      links: [
        {
          type: "Source",
          href: "https://github.com/sk394/Suman_MVC",
          icon: "",
        },
      ],
      image: "/nepbook.png",
      video: "",
    },
    {
      title: "Recipe Social",
      href: "/",
      dates: "Work in Progress",
      active: true,
      description: `A social media platform for food enthusiats...`,
      technologies: ["ASP.NET", "C#", "BootStrap"],
      links: [
        {
          type: "Source",
          href: "/",
          icon: "",
        },
      ],
      image: "",
      video: "",
    },
  ],
} as const;
